// src/types/author.ts

export interface AuthorDto {
  authorId: number;
  firstName: string;
  lastName: string;
}

export interface CreateAuthorDto {
  firstName: string;
  lastName: string;
  // No authorId here, as it's generated by the backend on creation
}

export interface UpdateAuthorDto {
  firstName?: string;
  lastName?: string;
}
