export interface GenreDto {
  id: number;
  name: string;
}

export interface CreateGenreDto {
  name: string;
  // No id here, as it's generated by the backend on creation
}

export interface UpdateGenreDto {
  name?: string;
}
